ServerName: TomO-Streaming
Port: 27025
VideoFolderPath: ""
ProcessingTomoImagingSignalFrequencyMs: 10
StreamingLenght: 0
MinValueRSlider: 1
MaxValueRSlider: 1
ValueSlider: 2
IsOnAllOverLay: true
IsOnDefect: true
IsOnOverKill: true
IsOnTracking: true
TomOCamFocus: TomoPose
OptispecCamFocus: OptiSpec
BomCamFocus: OCR
HeadCamFocus: Cuvette
IsMaxTomOCam: true
IsMaxOptispecCam: false
IsMaxBomCam: false
IsMaxHeadCam: false
BgColorCmd: "#000000"
TextFontCmd: "DejaVu Sans Mono"
TextSizeCmd: 12
TextColorCmd: "#FFFFFF"
LineSpacingCmd: 2
DisplayPanelStatus: false
MotionPanelStatus: false
HeightOfSystemlog: 210
YOfSystemlog: 843
TabOfSystemlog: 2
IsTomOC: false